const destinations = [
    {
      _id: 1,
      name: "Space Needle",
      location: "Seattle, WA",
      description: "An iconic landmark offering breathtaking views of Seattle and the surrounding landscapes.",
      activities: "Observation deck, Sky Café, VR experience",
      bestTime: "May to September",
      main_image: "space-needle.jpeg",
    },
    {
      _id: 2,
      name: "Olympic National Park",
      location: "Washington",
      description: "A national park featuring diverse ecosystems from rainforests to rugged coastlines.",
      activities: "Hiking, Wildlife watching, Camping",
      bestTime: "June to October",
      main_image: "olympic.png",
    },
    {
      _id: 3,
      name: "Leavenworth",
      location: "Washington",
      description: "A Bavarian-themed village with year-round outdoor activities and cultural events.",
      activities: "Wine tasting, Festivals, Hiking trails",
      bestTime: "December for holiday lights or September for fall activities",
      main_image: "leavenworth.jpeg",
    },
    {
      _id: 4,
      name: "Whistler",
      location: "British Columbia, Canada",
      description: "A popular ski resort offering activities all year round, from snow sports to mountain biking.",
      activities: "Skiing, Mountain biking, Zip-lining",
      bestTime: "December to February for skiing, June to August for biking",
      main_image: "whistler.jpeg",
    },
    {
      _id: 5,
      name: "Crater Lake",
      location: "Oregon",
      description: "The deepest lake in the U.S. with striking blue waters formed by a collapsed volcano.",
      activities: "Boat tours, Scenic drive, Photography",
      bestTime: "July to September",
      main_image: "crater-lake.jpeg",
    },
    {
      _id: 6,
      name: "The Gorge Amphitheatre",
      location: "Washington",
      description: "A stunning concert venue known for its natural acoustics and beautiful views of the Columbia River.",
      activities: "Concerts, Camping, Hiking",
      bestTime: "May to September",
      main_image: "the-gorge.jpeg",
    },
    {
      _id: 7,
      name: "Mount Rainier National Park",
      location: "Washington",
      description: "An iconic volcanic peak with beautiful wildflower meadows and hiking trails.",
      activities: "Climbing, Wildflower viewing, Snowshoeing",
      bestTime: "July to August",
      main_image: "mount-rainier.jpeg",
    },
    {
      _id: 8,
      name: "Portland Japanese Garden",
      location: "Portland, OR",
      description: "A beautiful traditional Japanese garden offering tranquil paths and scenic views.",
      activities: "Garden tour, Tea ceremony, Photography",
      bestTime: "March to May or September to November",
      main_image: "portland-garden.png",
    }
  ];
  
  module.exports = destinations;
  